version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Calc.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORT=57589
    ports:
      - "57589:80"